######################## default configuration ####################
baseURL = "https://www.daroca.eco.br"
languageCode = "en"
title = "Empório da Roça"
theme = "daroca"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  [[params.plugins.css]]
  link = "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"
  [[params.plugins.css]]
  link = "//cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "//cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"
  [[params.plugins.js]]
  link = "//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  [[params.plugins.js]]
  link = "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"
  [[params.plugins.js]]
  #link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  #[[menu.main]
  #name = "Produtos"
  #URL = "products"
  #weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 1


  [[menu.main]]
  name = "Contato"
  URL = "contact"
  weight = 2

#################### default parameters ################################
[params]
logo = "images/logo_daroca.png"
home = "Inicio"
productAsIndex = true
# Meta data
description = "Empório da Roça"
author = "BetaLinePat"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "5535998302864"
email = "vendas@daroca.eco.br"
location = "Piranguinho, Minas Gerais"
# copyright
copyright = "| Empório da Roça Produtos do Interior &copy; | Desenvolvido com [Hugo](https://gohugo.io/)"
# Snipcart Credentials
shopEnabled = false
snipcartApiKey = ""
currencySymbol = "R$ "

#PNGTree Licence
pngtree = "[some raw materials from pngtree](https://pngtree.com/so/raw-material) CC images"

 # Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Product Rating
# it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
[params.rating]
enable = false
websiteID = ""
publicKey = ""

  # Social Site
#  [[params.social]]
#  icon = "ti-facebook"
#  link = "#"
#
#  [[params.social]]
#  icon = "ti-twitter-alt"
#  link = "#"
#
#  [[params.social]]
#  icon = "ti-youtube"
#  link = "#"
#
#  [[params.social]]
#  icon = "ti-instagram"
#  link = "#"
#
#  [[params.social]]
#  icon = "ti-pinterest"
#  link = "#"

# Contact Form
[params.contact]
enable = false
formAction = "#" # contact form works with formspree.io
